apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amule-elarreglador-eu
  namespace: multimedia
spec:
  commonName: amule.elarreglador.eu
  dnsNames:
    - amule.elarreglador.eu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http
  secretName: amule-elarreglador-eu-tls
