apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: multimedia
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Madrid
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /ping
              port: 9696
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /ping
              port: 9696
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 9696
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
            - name: custom-defs
              mountPath: /config/Definitions/Custom
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-local
        - name: custom-defs
          configMap:
            name: prowlarr-custom-defs
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: multimedia
  labels:
    app: prowlarr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.57
  externalTrafficPolicy: Local
  selector:
    app: prowlarr
  ports:
    - port: 9696
      targetPort: 9696
