upstream torrent_upstream {
    server 10.8.0.11:6881;
}

server {
    listen 6881;
    proxy_pass torrent_upstream;
    proxy_timeout 300s;
}

server {
    listen 6881 udp;
    proxy_pass torrent_upstream;
    proxy_timeout 300s;
}
