[Interface]
PrivateKey = <PRIVATE_KEY_D2>
Address = 10.8.0.12/32,fd42:42:42::12/128
DNS = 10.8.0.1,1.8.0.1

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
PresharedKey = <PRESHARED_KEY_D2>
Endpoint = 82.223.50.169:51820
AllowedIPs = 10.8.0.1/32
PersistentKeepalive = 25
