[Interface]
PrivateKey = <PRIVATE_KEY_D1>
Address = 10.8.0.11/32,fd42:42:42::11/128
DNS = 10.8.0.1,1.8.0.1

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
PresharedKey = <PRESHARED_KEY_D1>
Endpoint = 82.223.50.169:51820
AllowedIPs = 0.0.0.0/0,::/0
PersistentKeepalive = 25
