apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage-v4
provisioner: nfs-storage
parameters:
  archiveOnDelete: "true"
mountOptions:
  - nfsvers=4.0
  - minorversion=0
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
